### ISSUE TITLE
org.jenkins-ci.plugins.workflow:workflow-aggregator:2.6 : Not able to build with UAT enabled. (Java Version Incompatibility)

### ISSUE THREAD

**Issue by shivsrivastava** [jenkinsci/plugin-installation-manager-tool#664]
### Jenkins and plugins versions report

While building org.jenkins-ci.plugins.workflow:workflow-aggregator:2.6 with mvn test , UAT fails.

Environment used.

Java (JDK) - 8, 11, 17
Build Command - mvn clean install -DskipTests
UAT command - mvn test

I am also attaching log file and  my exception here.

Please let me know working JDK and maven command to successfully run [UAT.]([build-workflow-aggregator-2.6-2024-02-29-03-52-07-240-6284025376.txt](https://github.com/jenkinsci/plugin-installation-manager-tool/files/14716410/build-workflow-aggregator-2.6-2024-02-29-03-52-07-240-6284025376.txt))

[29 04:01:23.571] | [ERROR] COMPILATION ERROR :
[29 04:01:23.571] | [INFO] -------------------------------------------------------------
[29 04:01:23.571] | [ERROR] /tmp/pkgs_raw/workflow-aggregator/2.6/target/generated-test-sources/injected/InjectedTest.java:[17,33] cannot find symbol
[29 04:01:23.571] | symbol:   class PluginAutomaticTestBuilder
[29 04:01:23.571] | location: package org.jvnet.hudson.test
[29 04:01:23.571] | [INFO] 1 error

### What Operating System are you using (both controller, and any agents involved in the problem)?

Using Windows and Ubuntu/Linux .

### Reproduction steps

NA

### Expected Results

UAT success

### Actual Results

UAT fails

### Anything else?

NA

### Are you interested in contributing a fix?

Na

**Comment by MarkEWaite** [comment]
The issue tracker in this repository is not the place to report an issue building workflow-aggregator.  You're more likely to get help if you describe details of your environment in the Jenkins community forum https://community.jenkins.io or the Jenkins chat channels, or the Jenkins user mailing list.

**Comment by shivsrivastava** [comment]
> The issue tracker in this repository is not the place to report an issue building workflow-aggregator. You're more likely to get help if you describe details of your environment in the Jenkins community forum https://community.jenkins.io or the Jenkins chat channels, or the Jenkins user mailing list.

We are not able to build with UT pass. Please provide an update with possible JDK version and Maven.

**Comment by MarkEWaite** [comment]
> We are not able to build with UT pass. Please provide an update with possible JDK version and Maven.

I don't understand why you would care about running the tests of the [workflow aggregator plugin](https://github.com/jenkinsci/workflow-aggregator-plugin), but you can see the results on [ci.jenkins.io with Java 8 and the current master branch](https://ci.jenkins.io/job/Plugins/job/workflow-aggregator-plugin/job/master/lastSuccessfulBuild/).  That build used Apache Maven 3.9.0 and Java 1.8.0_362.  It ran a year ago.  There have been no changes to the master branch since then.

There is a [pending pull request](https://github.com/jenkinsci/workflow-aggregator-plugin/pull/86) that uses Apache Maven 3.9.6 and Java 17.0.10 and Java 21.0.2.  That pull request builds and passes its tests with Apache Maven 3.9.6 and Java 21.0.2 on my Red Hat Enterprise Linux 8 computer and passes on Windows and Linux for ci.jenkins.io.  You can see the results of that configuration in the [ci.jenkins.io job pull request job](https://ci.jenkins.io/job/Plugins/job/workflow-aggregator-plugin/job/PR-86/lastSuccessfulBuild/).

Maybe you need the configuration advice that is listed in https://github.com/jenkins-infra/jenkins.io/pull/7194/files ?

If this does not address your question completely, please ask in one of the locations I mentioned earlier.  This is not the right place to discuss an issue with building and testing a specific Jenkins plugin.

**Comment by shivsrivastava** [comment]
> > We are not able to build with UT pass. Please provide an update with possible JDK version and Maven.
> 
> I don't understand why you would care about running the tests of the [workflow aggregator plugin](https://github.com/jenkinsci/workflow-aggregator-plugin), but you can see the results on [ci.jenkins.io with Java 8 and the current master branch](https://ci.jenkins.io/job/Plugins/job/workflow-aggregator-plugin/job/master/lastSuccessfulBuild/). That build used Apache Maven 3.9.0 and Java 1.8.0_362. It ran a year ago. There have been no changes to the master branch since then.
> 
> There is a [pending pull request](https://github.com/jenkinsci/workflow-aggregator-plugin/pull/86) that uses Apache Maven 3.9.6 and Java 17.0.10 and Java 21.0.2. That pull request builds and passes its tests with Apache Maven 3.9.6 and Java 21.0.2 on my Red Hat Enterprise Linux 8 computer and passes on Windows and Linux for ci.jenkins.io. You can see the results of that configuration in the [ci.jenkins.io job pull request job](https://ci.jenkins.io/job/Plugins/job/workflow-aggregator-plugin/job/PR-86/lastSuccessfulBuild/).
> 
> Maybe you need the configuration advice that is listed in https://github.com/jenkins-infra/jenkins.io/pull/7194/files ?
> 
> If this does not address your question completely, please ask in one of the locations I mentioned earlier. This is not the right place to discuss an issue with building and testing a specific Jenkins plugin.

Thanks , will check and confirm.

**Comment by devidandupati** [comment]
I have tried different jdk's like 17,8,15,11 and 18. but still getting failed

**Comment by meetankit24** [comment]
yes, getting failure for me also with some different version

**Comment by shivsrivastava** [comment]
Please update on it.
