### ISSUE TITLE
add instructions for the "bundled" `jenkins-plugin-cli` shell script

### ISSUE THREAD

**Issue by datalogics-robb** [jenkinsci/plugin-installation-manager-tool#752]
### Describe your use-case which is not covered by existing documentation.

In the README, it mentions the "bundled" `jenkins-plugin-cli` shell script - 

```
If you use a [Jenkins docker image](https://hub.docker.com/r/jenkins/jenkins) the plugin manager can be invoked inside the running container via the bundled jenkins-plugin-cli shell script:
```

I only see a jar file - and not being a primarily Java developer, I see nothing that would indicate where this script might be.  Would I need to unzip the jar file and find it somewhere inside?

### Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.

README.md at the top level

### Are you interested in contributing to the documentation?

interested but not able to

**Comment by MarkEWaite** [comment]
The [Jenkins controller container images](https://hub.docker.com/r/jenkins/jenkins) place the `jenkins-plugin-cli` script in `/usr/bin/`.  Since `/usr/bin` is in the PATH, it can be run with the command:

```
jenkins-plugin-cli --help
```

I confirmed that with the following Pipeline script on my Jenkins controller that is based on the Jenkins container image:

```
pipeline {
    agent {
        label 'built-in'
    }
    stages {
        stage('Plugin CLI help') {
            steps {
                sh 'jenkins-plugin-cli --help'
            }
        }
    }
}
```
